services:
  mongo:
    image: mongo:latest
    container_name: codequest-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: codequest
      MONGO_INITDB_ROOT_USERNAME: your_root_username
      MONGO_INITDB_ROOT_PASSWORD: your_root_password
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  minio:
    image: minio/minio:latest
    container_name: codequest-minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"

  app:
    build: .
    image: codequest-app:latest
    container_name: codequest-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://your_root_username:your_root_password@mongo:27017/codequest?authSource=admin
      - SESSION_SECRET=a-very-strong-random-string
      - FRONTEND_URL=https://your-domain.com
      - COOKIE_DOMAIN=your-domain.com
      - BASE_URL=https://your-domain.com
      - GOOGLE_CLIENT_ID=your_google_client_id
      - GOOGLE_CLIENT_SECRET=your_google_client_secret
      - GITHUB_CLIENT_ID=your_github_client_id
      - GITHUB_CLIENT_SECRET=your_github_client_secret
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_USE_SSL=false
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET_NAME=codequest-files
    depends_on:
      - mongo
      - minio
  postgres:
    image: postgres:14
    container_name: codequest-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: your_pg_user
      POSTGRES_PASSWORD: your_pg_password
      POSTGRES_DB: codequest
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  mongo-data:
  minio-data:
  postgres-data:
