services:
  mongo:
    image: mongo:latest
    container_name: codequest-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: codequest
      MONGO_INITDB_ROOT_USERNAME: your_root_username
      MONGO_INITDB_ROOT_PASSWORD: your_root_password

volumes:
  mongo-data: